export const ADD_SEARCH_PARAMS = 'ADD_SEARCH_PARAMS';
export const CLEAR_SEARCH_PARAMS = 'CLEAR_SEARCH_PARAMS';
export const ADD_ITINERARY = 'ADD_ITINERARY';
export const CLEAR_ITINERARY = 'CLEAR_ITINERARY';
export const ADD_GEOJSON = 'ADD_GEOJSON';
export const CLEAR_GEOJSON = 'CLEAR_GEOJSON';


